import { Montserrat, Unna } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import Header from "@/components/Ui/Header";
import Footer from "@/components/Ui/Footer";

/* const inter = Inter({ subsets: ["latin"] }); */
export const montserrat = Montserrat({
  weight: ['100','200','300','400','500','600','700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});
 
export const unna = Unna({  
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-unna',
});

export const metadata = {
  title: "Viñedo Ain Karim",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="es">
      <body className={`${montserrat.variable} ${unna.variable}`}>
      <Header/>      
        <AppRouterCacheProvider>{props.children}</AppRouterCacheProvider>
      <Footer/>
      </body>
    </html>
  );
}
